[package]
name = "wiz"
version = "0.1.0"
authors = ["hch12907 <haochengho12907@gmail.com>"]

[dependencies]
clap = "2.6.0"
flate2 = "0.2.14" 
tar = "0.4.6"
crc = "1.3.0"
hyper = "0.9.10"
serde_json = "0.8.2"