[package]
name = "wiz"
version = "0.1.0"
authors = ["hch12907 <haochengho12907@gmail.com>"]

[dependencies]
clap = "2.18.0"
flate2 = "0.2.14" 
tar = "0.4.8"
crc = "1.3.0"
hyper = { version = "0.9.12", default-features = false }
serde = "0.8.17"
serde_json = "0.8.3"
rustc-serialize = "0.3.21"